# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7626d975d4131bb1e56b3fa97700dc29da178394c61f96786ddb398b436c3af0fad6a1209e8931402e4ad206919a79946cb91e1d886ef264e9ebdea0bcdb90c

test:
  secret_key_base: 8b86521bdf20106c247c7109377ce04288f18a67c422e4940e26a2754db608ffeafb154b6a0a27efacaa08c031c188d021c089b1f0eaa623a5638bb3a80385f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
